### ISSUE TITLE
Webclient: Basic front-end

### ISSUE THREAD

**Issue by grovecj** [CSSE497/pathfinder-webclient#1]
### Features

- [x] Landing Page
- [x] Registration/Login Form  
~~- [ ] App Creation~~ Out of scope for sprint 3
- [x]  Cluster/Commodity/Vehicle CRUD  
- [x]  Route Generation  
- [x]  Route Visualization  

### Miscellania  
- [x] Refactor api url into configuration file  
~~- [ ] Hide 'Add Child' button when no cluster is selected~~ Out of scope for sprint 3

**Comment by aj-michael** [comment]
@grovecj: How many actual hours did this take you? And how many more do you think it will bleed into next sprint?

**Comment by grovecj** [comment]
It was probably about 5 each for the map part and the cluster explorer part. I have about 30 more minutes of integrating with david's login stuff to do still. **Call it 10.5 for this week** and 3-7 next week depending on if we get clusters/accounts/apps working
