### ISSUE TITLE
App Look & Feel

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-webclient#6]
* [x] App should draw all routes that pushed to it
* [x] Only one marker should be drawn for commodities on each route
* [x] Commodity markers should be visually distinct

**Comment by aj-michael** [comment]
To my knowledge, this was not attempted this sprint. Hopefully @grovecj can chime in to clarify.

Pushing it back to Sprint 5.

**Comment by grovecj** [comment]
This has taken about 2.5 hours
